
default: &default
  adapter: postgresql
  encoding: unicode
 
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: demop_development
  username: harry
  password: harry123
  host: localhost

test:
  <<: *default
  encoding: unicode
  username: harry
  password: harry123
  database: demop_test

production:
  <<: *default
  database: demop_production
  username: harry
  password: harry123